---
# Reference: https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
require:
  - rubocop-faker
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/tasks/*'
    - 'Rakefile'
    - '*.gemspec'
    - '**/node_modules/**/*'
    - 'vendor/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - config/environments/production.rb
    - config/environments/test.rb

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Exclude:
    - config/application.rb
    - app/controllers/application_controller.rb
    - app/models/application_record.rb
