---
# Reference: https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
require:
  - rubocop-faker
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/tasks/*'
    - 'Rakefile'
    - '*.gemspec'
    - '**/node_modules/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Exclude:
    - config/routes.rb

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Exclude:
    - app/controllers/**/*
    - app/helpers/application_helper.rb
    - app/models/application_record.rb
    - config/application.rb
    - spec/**/*
    - test/**/*
